// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnowdqnqyrcuzpmosryc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ub3dkcW5xeXJjdXpwbW9zcnljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzA0MjAsImV4cCI6MjA2NDk0NjQyMH0.1sciQUNdVisbt5UZVeSTJDXjDRrfuTawPgRBedGTDaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);